export const CAR_MAKE_LIST_REQUEST = 'CAR_MAKE_LIST_REQUEST';
export const CAR_MAKE_LIST_SUCCESS = 'CAR_MAKE_LIST_SUCCESS';
export const CAR_MAKE_LIST_FAIL = 'CAR_MAKE_LIST_FAIL';

export const CAR_MODEL_LIST_REQUEST = 'CAR_MODEL_LIST_REQUEST';
export const CAR_MODEL_LIST_SUCCESS = 'CAR_MODEL_LIST_SUCCESS';
export const CAR_MODEL_LIST_FAIL = 'CAR_MODEL_LIST_FAIL';

export const CAR_YEAR_LIST_REQUEST = 'CAR_YEAR_LIST_REQUEST';
export const CAR_YEAR_LIST_SUCCESS = 'CAR_YEAR_LIST_SUCCESS';
export const CAR_YEAR_LIST_FAIL = 'CAR_YEAR_LIST_FAIL';

export const CAR_SIZE_LIST_REQUEST = 'CAR_SIZE_LIST_REQUEST';
export const CAR_SIZE_LIST_SUCCESS = 'CAR_SIZE_LIST_SUCCESS';
export const CAR_SIZE_LIST_FAIL = 'CAR_SIZE_LIST_FAIL';