export const NEW_ORDER_INFORMAION_DETAILS = "NEW_ORDER_INFORMAION_DETAILS";

export const NEW_ORDER_PAYMENT_METHOD = "NEW_ORDER_PAYMENT_METHOD";

export const CALCULATE_COST_REQUEST = "CALCULATE_COST_REQUEST";
export const CALCULATE_COST_SUCCESS = "CALCULATE_COST_SUCCESS";
export const CALCULATE_COST_FAIL = "CALCULATE_COST_FAIL";

export const NEW_ORDER_REQUEST = "NEW_ORDER_REQUEST";
export const NEW_ORDER_SUCCESS = "NEW_ORDER_SUCCESS";
export const NEW_ORDER_FAIL = "NEW_ORDER_FAIL";

export const NEW_ORDER_CAR_REQUEST = "NEW_ORDER_CAR_REQUEST";
export const NEW_ORDER_CAR_SUCCESS = "NEW_ORDER_CAR_SUCCESS";
export const NEW_ORDER_CAR_FAIL = "NEW_ORDER_CAR_FAIL";