export const ZIP_CODE_FROM_REQUEST = 'ZIP_CODE_FROM_REQUEST';
export const ZIP_CODE_FROM_SUCCESS = 'ZIP_CODE_FROM_SUCCESS';
export const ZIP_CODE_FROM_FAIL = 'ZIP_CODE_FROM_FAIL';

export const ZIP_CODE_TO_REQUEST = 'ZIP_CODE_TO_REQUEST';
export const ZIP_CODE_TO_SUCCESS = 'ZIP_CODE_TO_SUCCESS';
export const ZIP_CODE_TO_FAIL = 'ZIP_CODE_TO_FAIL';