import React from "react";
import { Row, Col, Container } from "react-bootstrap";
import "react-responsive-carousel/lib/styles/carousel.min.css";
import { Carousel } from "react-responsive-carousel";

export default class HowItWorks extends React.Component {
  render() {
    var settings = {
      autoPlay: true,
      showArrows: false,
      showThumbs: false,
      showStatus: false,
      infiniteLoop: true,
    };
    return (
      <section className="section how-it-works">
        <Container>
          <h1 className="section-main-title">How It Works?</h1>
          <Carousel {...settings}>
            <Row className="carousel-row">
              <Col xs={12} md={6} className="left">
                <div className="wrapper">
                  <div class="icon4">
                    <svg id="icon4" viewBox="0 0 140 140">
                      <g id="line1" class="line1">
                        <rect
                          x="39"
                          y="45"
                          fill="#193b48"
                          width="9"
                          height="2"
                        />
                        <rect
                          x="70"
                          y="49"
                          fill="#CCCCCC"
                          width="11"
                          height="2"
                        />
                        <rect
                          x="83"
                          y="49"
                          fill="#CCCCCC"
                          width="16"
                          height="2"
                        />
                        <rect
                          x="43"
                          y="49"
                          fill="#CCCCCC"
                          width="25"
                          height="2"
                        />
                      </g>
                      <g id="line2" class="line2">
                        <rect
                          x="90"
                          y="53"
                          fill="#CCCCCC"
                          width="14"
                          height="2"
                        />
                        <rect
                          x="63"
                          y="53"
                          fill="#CCCCCC"
                          width="25"
                          height="2"
                        />
                        <rect
                          x="43"
                          y="53"
                          fill="#CCCCCC"
                          width="18"
                          height="2"
                        />
                        <rect
                          x="57"
                          y="57"
                          fill="#CCCCCC"
                          width="22"
                          height="2"
                        />
                        <rect
                          x="43"
                          y="57"
                          fill="#CCCCCC"
                          width="12"
                          height="2"
                        />
                      </g>
                      <g id="line3" class="line3">
                        <rect
                          x="39"
                          y="61"
                          fill="#193b48"
                          width="9"
                          height="2"
                        />
                        <rect
                          x="39"
                          y="65"
                          fill="#193b48"
                          width="15"
                          height="2"
                        />
                      </g>
                      <g id="line4" class="line4">
                        <rect
                          x="46"
                          y="69"
                          fill="#CCCCCC"
                          width="10"
                          height="2"
                        />
                        <rect
                          x="58"
                          y="69"
                          fill="#CCCCCC"
                          width="43"
                          height="2"
                        />
                        <rect
                          x="103"
                          y="69"
                          fill="#CCCCCC"
                          width="9"
                          height="2"
                        />
                        <rect
                          x="78"
                          y="73"
                          fill="#CCCCCC"
                          width="38"
                          height="2"
                        />
                        <rect
                          x="52"
                          y="73"
                          fill="#CCCCCC"
                          width="24"
                          height="2"
                        />
                      </g>
                      <g id="line5" class="line5">
                        <rect
                          x="103"
                          y="81"
                          fill="#CCCCCC"
                          width="13"
                          height="2"
                        />
                        <rect
                          x="76"
                          y="81"
                          fill="#CCCCCC"
                          width="25"
                          height="2"
                        />
                        <rect
                          x="56"
                          y="81"
                          fill="#CCCCCC"
                          width="18"
                          height="2"
                        />
                        <rect
                          x="89"
                          y="77"
                          fill="#CCCCCC"
                          width="10"
                          height="2"
                        />
                        <rect
                          x="61"
                          y="77"
                          fill="#CCCCCC"
                          width="26"
                          height="2"
                        />
                        <rect
                          x="52"
                          y="77"
                          fill="#CCCCCC"
                          width="7"
                          height="2"
                        />
                      </g>
                      <g id="line6" class="line6">
                        <rect
                          x="46"
                          y="89"
                          fill="#CCCCCC"
                          width="11"
                          height="2"
                        />
                        <rect
                          x="52"
                          y="85"
                          fill="#CCCCCC"
                          width="10"
                          height="2"
                        />
                        <rect
                          x="64"
                          y="85"
                          fill="#CCCCCC"
                          width="19"
                          height="2"
                        />
                        <rect
                          x="85"
                          y="85"
                          fill="#CCCCCC"
                          width="19"
                          height="2"
                        />
                        <rect
                          x="59"
                          y="89"
                          fill="#CCCCCC"
                          width="6"
                          height="2"
                        />
                      </g>
                      <g id="computer">
                        <path
                          fill="#CCCCCC"
                          d="M128,108H12V26h116V108z M14,106h112V28H14V106z"
                        />
                        <path
                          fill="#CCCCCC"
                          d="M122,102H18V32h104V102z M20,100h100V34H20V100z"
                        />
                        <rect
                          x="20"
                          y="34"
                          fill="#193b48"
                          width="100"
                          height="7"
                        />
                        <path
                          fill="#CCCCCC"
                          d="M138,115H2v-9h136V115z M4,113h132v-5H4V113z"
                        />
                        <circle fill="#FFFFFF" cx="24.5" cy="37.5" r="1.5" />
                        <circle fill="#FFFFFF" cx="29.5" cy="37.5" r="1.5" />
                        <circle fill="#FFFFFF" cx="34.5" cy="37.5" r="1.5" />
                        <rect
                          x="20"
                          y="41"
                          fill="#F2F2F2"
                          width="15"
                          height="59"
                        />
                        <path
                          fill="#CCCCCC"
                          d="M84,111H56v-5h28V111z M58,109h24v-1H58V109z"
                        />
                        <circle fill="#CCCCCC" cx="72" cy="30" r="1" />
                      </g>
                    </svg>
                  </div>
                </div>
              </Col>
              <Col xs={12} md={6} className="right">
                <h3>
                  Schedule a car shipment <br></br>
                  <span>online or over the phone.</span>
                </h3>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco
                  laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                  irure dolor in reprehenderit in voluptate velit esse cillum
                  dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                  cupidatat non proident, sunt in culpa qui officia deserunt
                  mollit anim id est laborum.
                </p>
              </Col>
            </Row>
            <Row className="carousel-row">
              <Col xs={12} md={6} className="left">
                <div className="wrapper">
                  <div class="icon6">
                    <svg id="icon6" viewBox="0 0 140 140">
                      <g id="truck" class="truck">
                        <rect
                          x="22"
                          y="84"
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="110"
                          height="13"
                        />
                        <polygon
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          points="93.1,84 22,84 22,34 87,34 93.1,41.1 	
                                                                                                 "
                        />
                        <polygon
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          points="132,84 93,84 93,41 119,41 122,59 
                                                                                                 132,64 	"
                        />
                        <polyline
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          points="122,59 99,59 99,45 120,45 	"
                        />
                        <rect
                          x="81"
                          y="92"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="22"
                          height="7"
                        />
                        <rect
                          x="128"
                          y="70"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="4"
                          height="7"
                        />
                        <rect
                          x="99"
                          y="64"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="4"
                          height="1"
                        />
                        <rect
                          x="132"
                          y="88"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="3"
                          height="9"
                        />
                        <rect
                          x="19"
                          y="91"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="3"
                          height="4"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-miterlimit="10"
                          x1="105"
                          y1="48"
                          x2="102"
                          y2="51"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-miterlimit="10"
                          x1="102"
                          y1="54"
                          x2="108"
                          y2="48"
                        />
                        <g enable-background="new">
                          <path
                            fill="#193b48"
                            d="M34.9,47.6h5.2V63h-5.2V47.6z"
                          />
                          <path
                            fill="#193b48"
                            d="M41.9,47.6h12.9V52H47v2h7.2v4H47v5h-5.2V47.6H41.9z"
                          />
                          <path
                            fill="#193b48"
                            d="M56,47.6h5.4l3.3,5.4l3.3-5.4h5.4V63h-5.1v-7.6l-3.5,5.5h-0.1l-3.5-5.5V63h-5V47.6H56z"
                          />
                          <path
                            fill="#193b48"
                            d="M74.8,57.9h5.1V63h-5.1V57.9z"
                          />
                        </g>
                        <g enable-background="new">
                          <path
                            fill="#CCCCCC"
                            d="M35.5,68.5l5.3-2.1v1.5L39,68.6l-1.5,0.5l0,0l1.5,0.5l1.8,0.6v1.5l-5.3-2.1V68.5z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M44.4,64.7h1.2l-4.1,10.2h-1.2L44.4,64.7z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M48.5,67c0.7,0,1.3,0.4,1.6,0.7l-1,1.1c-0.2-0.2-0.4-0.3-0.7-0.3c-0.8,0-1.5,1-1.5,2.2c0,0.6,0.3,1,0.8,1
                                  c0.4,0,0.6-0.2,0.8-0.3l0.8,1.1c-0.4,0.3-1.1,0.7-2,0.7c-1.3,0-2.3-0.9-2.3-2.4C44.9,68.7,46.4,67,48.5,67z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M50,70.7c0-2.3,1.7-3.7,3.3-3.7c1.4,0,2.3,1,2.3,2.4c0,2.3-1.7,3.7-3.3,3.7C50.9,73.1,50,72.2,50,70.7z
                                  M51.9,70.7c0,0.6,0.2,1,0.7,1c0.7,0,1.2-0.9,1.2-2.2c0-0.6-0.2-1-0.7-1C52.4,68.5,51.9,69.4,51.9,70.7z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M60.7,66.6l0.3-1.7h1.9L61.3,73h-1.5v-0.7l0,0c-0.5,0.5-1.2,0.9-1.8,0.9c-1,0-1.6-0.8-1.6-2.2
                                  c0-2.2,1.5-4,3.1-4c0.5,0,0.9,0.3,1.1,0.7l0,0L60.7,66.6z M59.9,70.8l0.4-1.9c-0.1-0.3-0.4-0.4-0.6-0.4c-0.7,0-1.3,0.9-1.3,2.2
                                  c0,0.6,0.2,0.9,0.5,0.9C59.1,71.6,59.5,71.5,59.9,70.8z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M66.1,67c1.4,0,1.9,1,1.9,2.2c0,0.6-0.2,1.2-0.3,1.4h-3.2c0,0.8,0.5,1.1,1.2,1.1c0.3,0,0.7-0.2,1-0.4
                                  l0.7,1.2c-0.5,0.3-1.2,0.6-2.2,0.6c-1.4,0-2.4-1-2.4-2.5C62.8,68.5,64.5,67,66.1,67z M66.4,69.5c0-0.1,0-0.2,0-0.4
                                  c0-0.4-0.2-0.7-0.7-0.7c-0.4,0-0.9,0.3-1.2,1.1H66.4z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M68.9,70.3l1.8-0.6l1.5-0.5l0,0l-1.5-0.5l-1.8-0.6v-1.5l5.3,2.1V70l-5.3,2.1V70.3z"
                          />
                        </g>
                      </g>
                      <g id="cloud" class="cloud">
                        <path
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-miterlimit="10"
                          d="M14,91c0-1.7-1.3-3-3-3c-1.4,0-2.6,1-2.9,2.3
                                                                        C7.8,90.1,7.4,90,7,90c-0.8,0-1.5,0.5-1.8,1.2C5,91.1,4.7,91,4.5,91C3.7,91,3,91.7,3,92.5S3.7,94,4.5,94c0.2,0,0.4,0,0.5-0.1V94
                                                                        c0,0.1,0,0.1,0,0.2s0,0.2,0,0.3C5,95.3,5.7,96,6.5,96c0.5,0,0.9-0.2,1.1-0.5C8,95.8,8.5,96,9,96s0.9-0.2,1.2-0.4
                                                                        c0.4,0.9,1.3,1.4,2.3,1.4c1.3,0,2.4-1,2.5-2.3c0.6-0.3,1-1,1-1.7C16,91.9,15.1,91,14,91z"
                        />
                      </g>
                      <g transform="translate(70 70)">
                        <g id="wheel3" class="wheel3">
                          <g transform="translate(-70 -70)">
                            <path
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              d="M27.9,93.2c-2.1,4.5-0.2,9.8,4.3,12
                                                                                         c4.5,2.1,9.8,0.2,12-4.3c2.1-4.5,0.2-9.8-4.3-12S30,88.7,27.9,93.2z"
                            />
                            <circle
                              fill="#FFFFFF"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              cx="36"
                              cy="97"
                              r="3"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="39"
                              y1="90.7"
                              x2="39.8"
                              y2="88.9"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="42.4"
                              y1="100"
                              x2="44.2"
                              y2="100.8"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="33.1"
                              y1="103.4"
                              x2="32.2"
                              y2="105.2"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="29.7"
                              y1="94.1"
                              x2="27.9"
                              y2="93.2"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="27.6"
                              y1="100.1"
                              x2="30.4"
                              y2="99.1"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="39.1"
                              y1="105.5"
                              x2="38.1"
                              y2="102.7"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="44.5"
                              y1="93.9"
                              x2="41.7"
                              y2="95"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="32.9"
                              y1="88.6"
                              x2="34"
                              y2="91.4"
                            />
                          </g>
                        </g>
                      </g>
                      <g id="wheel2" class="wheel2">
                        <path
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          d="M49.7,93.7c-1.8,4.7,0.4,9.8,5.1,11.7
                                                                                         c4.7,1.8,9.8-0.4,11.7-5.1c1.8-4.7-0.4-9.8-5.1-11.7C56.7,86.8,51.5,89.1,49.7,93.7z"
                        />
                        <circle
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          cx="58"
                          cy="97"
                          r="3"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="60.6"
                          y1="90.5"
                          x2="61.3"
                          y2="88.6"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="64.6"
                          y1="99.6"
                          x2="66.4"
                          y2="100.3"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="55.5"
                          y1="103.5"
                          x2="54.7"
                          y2="105.4"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="51.5"
                          y1="94.5"
                          x2="49.7"
                          y2="93.7"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="49.8"
                          y1="100.6"
                          x2="52.5"
                          y2="99.4"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="61.6"
                          y1="105.3"
                          x2="60.4"
                          y2="102.5"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="66.3"
                          y1="93.4"
                          x2="63.5"
                          y2="94.6"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="54.5"
                          y1="88.8"
                          x2="55.6"
                          y2="91.5"
                        />
                      </g>
                      <g id="wheel1" class="wheel1">
                        <path
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          d="M110.8,93.4c-2,4.6,0,9.8,4.6,11.9
                                                                                         c4.6,2,9.8,0,11.9-4.6c2-4.6,0-9.8-4.6-11.9C118.1,86.8,112.8,88.8,110.8,93.4z"
                        />
                        <circle
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          cx="119"
                          cy="97"
                          r="3"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="121.9"
                          y1="90.6"
                          x2="122.7"
                          y2="88.8"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="125.4"
                          y1="99.9"
                          x2="127.2"
                          y2="100.7"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="116.2"
                          y1="103.4"
                          x2="115.4"
                          y2="105.2"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="112.6"
                          y1="94.2"
                          x2="110.8"
                          y2="93.4"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="110.6"
                          y1="100.2"
                          x2="113.4"
                          y2="99.2"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="122.2"
                          y1="105.4"
                          x2="121.2"
                          y2="102.6"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="127.4"
                          y1="93.8"
                          x2="124.6"
                          y2="94.9"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="115.8"
                          y1="88.6"
                          x2="116.9"
                          y2="91.4"
                        />
                      </g>
                      <line
                        id="floor"
                        class="floor"
                        fill="none"
                        stroke="#E8E8E8"
                        stroke-width="2"
                        stroke-miterlimit="10"
                        x1="12"
                        y1="108"
                        x2="140"
                        y2="108"
                      />
                    </svg>
                  </div>
                </div>
              </Col>
              <Col xs={12} md={6} className="right">
                <h3>
                  We pick up your car and the <br></br>
                  <span>vehicle transport journey begins.</span>
                </h3>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco
                  laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                  irure dolor in reprehenderit in voluptate velit esse cillum
                  dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                  cupidatat non proident, sunt in culpa qui officia deserunt
                  mollit anim id est laborum.
                </p>
              </Col>
            </Row>
            <Row className="carousel-row">
              <Col xs={12} md={6} className="left">
                <div className="wrapper">
                  <div class="icon2">
                    <svg id="icon2" viewBox="0 0 140 140">
                      <g id="frame" class="ratio_frame">
                        <rect
                          x="11"
                          y="30"
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="117"
                          height="80"
                        />
                        <rect
                          x="11"
                          y="30"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="117"
                          height="9"
                        />
                        <circle fill="#CCCCCC" cx="123.5" cy="34.5" r="1.5" />
                        <circle fill="#CCCCCC" cx="118.5" cy="34.5" r="1.5" />
                        <circle fill="#CCCCCC" cx="113.5" cy="34.5" r="1.5" />
                      </g>
                      <g id="image" class="ratio_image">
                        <rect
                          x="18"
                          y="71"
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="31"
                          height="25"
                        />
                        <circle
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          cx="40.5"
                          cy="78.5"
                          r="2.5"
                        />
                        <polyline
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          points="18,79 23,77 31,89 36,85 45,96"
                        />
                      </g>
                      <g id="text" class="ratio_text">
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="74"
                          y1="71"
                          x2="119"
                          y2="71"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="74"
                          y1="76"
                          x2="119"
                          y2="76"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="74"
                          y1="81"
                          x2="119"
                          y2="81"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="62"
                          y1="91"
                          x2="119"
                          y2="91"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="62"
                          y1="96"
                          x2="119"
                          y2="96"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="62"
                          y1="86"
                          x2="119"
                          y2="86"
                        />
                        <polyline
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          points="63,82 63,71 69,71 69,82"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="63"
                          y1="77"
                          x2="69"
                          y2="77"
                        />
                      </g>
                      <g id="head" class="ratio_head">
                        <rect
                          x="110"
                          y="49"
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="8"
                          height="2"
                        />
                        <rect
                          x="98"
                          y="49"
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="8"
                          height="2"
                        />
                        <rect
                          x="86"
                          y="49"
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="8"
                          height="2"
                        />
                        <rect
                          x="74"
                          y="49"
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="8"
                          height="2"
                        />
                        <circle
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          cx="24"
                          cy="50"
                          r="5"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="11"
                          y1="61"
                          x2="128"
                          y2="61"
                        />
                      </g>
                      <g id="box" class="ratio_box">
                        <polyline
                          fill="none"
                          stroke="#193b48"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          points="37,37 54,37 54,54 	"
                        />
                        <rect
                          x="45"
                          y="54"
                          fill="none"
                          stroke="#193b48"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="9"
                          height="12"
                        />
                        <rect
                          x="9"
                          y="37"
                          fill="none"
                          stroke="#193b48"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="28"
                          height="29"
                        />
                        <rect
                          x="9"
                          y="66"
                          fill="none"
                          stroke="#193b48"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="45"
                          height="46"
                        />
                        <rect
                          x="54"
                          y="37"
                          fill="none"
                          stroke="#193b48"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="76"
                          height="75"
                        />
                        <rect
                          x="37"
                          y="54"
                          fill="none"
                          stroke="#193b48"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="8"
                          height="6"
                        />
                        <rect
                          x="37"
                          y="60"
                          fill="none"
                          stroke="#193b48"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="8"
                          height="6"
                        />
                      </g>
                      <path
                        id="line"
                        class="ratio_line"
                        fill="none"
                        stroke="#193b48"
                        stroke-width="2"
                        stroke-miterlimit="10"
                        d="M42,60c1.9,0,3.1-1.2,3-3l0,0
                                                                                                                 c0-1.9-1.2-3-3-3l0,0c-2.9,0-5,2-5,5l0,0c0,3.7,3.3,7,7,7l0,0c6.1,0,10-5.9,10-12l0,0c0-9.8-6.6-17-16.4-17l0,0
                                                                                                                 C21.8,37,9,49.8,9,65.7l0,0C9,91.5,29.5,112,55.2,112l0,0c41.6,0,74.8-33.3,74.8-75"
                      />
                    </svg>
                  </div>
                </div>
              </Col>
              <Col xs={12} md={6} className="right">
                <h3>
                  You track your car <br></br>
                  <span>online or over the phone.</span>
                </h3>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco
                  laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                  irure dolor in reprehenderit in voluptate velit esse cillum
                  dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                  cupidatat non proident, sunt in culpa qui officia deserunt
                  mollit anim id est laborum.
                </p>
              </Col>
            </Row>
            <Row className="carousel-row">
              <Col xs={12} md={6} className="left">
                <div className="wrapper">
                  <div class="icon6">
                    <svg id="icon6" viewBox="0 0 140 140">
                      <g id="truck" class="truck">
                        <rect
                          x="22"
                          y="84"
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="110"
                          height="13"
                        />
                        <polygon
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          points="93.1,84 22,84 22,34 87,34 93.1,41.1 	
                                                                                                 "
                        />
                        <polygon
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          points="132,84 93,84 93,41 119,41 122,59 
                                                                                                 132,64 	"
                        />
                        <polyline
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          points="122,59 99,59 99,45 120,45 	"
                        />
                        <rect
                          x="81"
                          y="92"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="22"
                          height="7"
                        />
                        <rect
                          x="128"
                          y="70"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="4"
                          height="7"
                        />
                        <rect
                          x="99"
                          y="64"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="4"
                          height="1"
                        />
                        <rect
                          x="132"
                          y="88"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="3"
                          height="9"
                        />
                        <rect
                          x="19"
                          y="91"
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          width="3"
                          height="4"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-miterlimit="10"
                          x1="105"
                          y1="48"
                          x2="102"
                          y2="51"
                        />
                        <line
                          fill="none"
                          stroke="#CCCCCC"
                          stroke-miterlimit="10"
                          x1="102"
                          y1="54"
                          x2="108"
                          y2="48"
                        />
                        <g enable-background="new">
                          <path
                            fill="#193b48"
                            d="M34.9,47.6h5.2V63h-5.2V47.6z"
                          />
                          <path
                            fill="#193b48"
                            d="M41.9,47.6h12.9V52H47v2h7.2v4H47v5h-5.2V47.6H41.9z"
                          />
                          <path
                            fill="#193b48"
                            d="M56,47.6h5.4l3.3,5.4l3.3-5.4h5.4V63h-5.1v-7.6l-3.5,5.5h-0.1l-3.5-5.5V63h-5V47.6H56z"
                          />
                          <path
                            fill="#193b48"
                            d="M74.8,57.9h5.1V63h-5.1V57.9z"
                          />
                        </g>
                        <g enable-background="new">
                          <path
                            fill="#CCCCCC"
                            d="M35.5,68.5l5.3-2.1v1.5L39,68.6l-1.5,0.5l0,0l1.5,0.5l1.8,0.6v1.5l-5.3-2.1V68.5z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M44.4,64.7h1.2l-4.1,10.2h-1.2L44.4,64.7z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M48.5,67c0.7,0,1.3,0.4,1.6,0.7l-1,1.1c-0.2-0.2-0.4-0.3-0.7-0.3c-0.8,0-1.5,1-1.5,2.2c0,0.6,0.3,1,0.8,1
                                  c0.4,0,0.6-0.2,0.8-0.3l0.8,1.1c-0.4,0.3-1.1,0.7-2,0.7c-1.3,0-2.3-0.9-2.3-2.4C44.9,68.7,46.4,67,48.5,67z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M50,70.7c0-2.3,1.7-3.7,3.3-3.7c1.4,0,2.3,1,2.3,2.4c0,2.3-1.7,3.7-3.3,3.7C50.9,73.1,50,72.2,50,70.7z
                                  M51.9,70.7c0,0.6,0.2,1,0.7,1c0.7,0,1.2-0.9,1.2-2.2c0-0.6-0.2-1-0.7-1C52.4,68.5,51.9,69.4,51.9,70.7z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M60.7,66.6l0.3-1.7h1.9L61.3,73h-1.5v-0.7l0,0c-0.5,0.5-1.2,0.9-1.8,0.9c-1,0-1.6-0.8-1.6-2.2
                                  c0-2.2,1.5-4,3.1-4c0.5,0,0.9,0.3,1.1,0.7l0,0L60.7,66.6z M59.9,70.8l0.4-1.9c-0.1-0.3-0.4-0.4-0.6-0.4c-0.7,0-1.3,0.9-1.3,2.2
                                  c0,0.6,0.2,0.9,0.5,0.9C59.1,71.6,59.5,71.5,59.9,70.8z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M66.1,67c1.4,0,1.9,1,1.9,2.2c0,0.6-0.2,1.2-0.3,1.4h-3.2c0,0.8,0.5,1.1,1.2,1.1c0.3,0,0.7-0.2,1-0.4
                                  l0.7,1.2c-0.5,0.3-1.2,0.6-2.2,0.6c-1.4,0-2.4-1-2.4-2.5C62.8,68.5,64.5,67,66.1,67z M66.4,69.5c0-0.1,0-0.2,0-0.4
                                  c0-0.4-0.2-0.7-0.7-0.7c-0.4,0-0.9,0.3-1.2,1.1H66.4z"
                          />
                          <path
                            fill="#CCCCCC"
                            d="M68.9,70.3l1.8-0.6l1.5-0.5l0,0l-1.5-0.5l-1.8-0.6v-1.5l5.3,2.1V70l-5.3,2.1V70.3z"
                          />
                        </g>
                      </g>
                      <g id="cloud" class="cloud">
                        <path
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-miterlimit="10"
                          d="M14,91c0-1.7-1.3-3-3-3c-1.4,0-2.6,1-2.9,2.3
                                                                        C7.8,90.1,7.4,90,7,90c-0.8,0-1.5,0.5-1.8,1.2C5,91.1,4.7,91,4.5,91C3.7,91,3,91.7,3,92.5S3.7,94,4.5,94c0.2,0,0.4,0,0.5-0.1V94
                                                                        c0,0.1,0,0.1,0,0.2s0,0.2,0,0.3C5,95.3,5.7,96,6.5,96c0.5,0,0.9-0.2,1.1-0.5C8,95.8,8.5,96,9,96s0.9-0.2,1.2-0.4
                                                                        c0.4,0.9,1.3,1.4,2.3,1.4c1.3,0,2.4-1,2.5-2.3c0.6-0.3,1-1,1-1.7C16,91.9,15.1,91,14,91z"
                        />
                      </g>
                      <g transform="translate(70 70)">
                        <g id="wheel3" class="wheel3">
                          <g transform="translate(-70 -70)">
                            <path
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              d="M27.9,93.2c-2.1,4.5-0.2,9.8,4.3,12
                                                                                         c4.5,2.1,9.8,0.2,12-4.3c2.1-4.5,0.2-9.8-4.3-12S30,88.7,27.9,93.2z"
                            />
                            <circle
                              fill="#FFFFFF"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              cx="36"
                              cy="97"
                              r="3"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="39"
                              y1="90.7"
                              x2="39.8"
                              y2="88.9"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="42.4"
                              y1="100"
                              x2="44.2"
                              y2="100.8"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="33.1"
                              y1="103.4"
                              x2="32.2"
                              y2="105.2"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="29.7"
                              y1="94.1"
                              x2="27.9"
                              y2="93.2"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="27.6"
                              y1="100.1"
                              x2="30.4"
                              y2="99.1"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="39.1"
                              y1="105.5"
                              x2="38.1"
                              y2="102.7"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="44.5"
                              y1="93.9"
                              x2="41.7"
                              y2="95"
                            />
                            <line
                              fill="#F2F2F2"
                              stroke="#CCCCCC"
                              stroke-width="2"
                              stroke-miterlimit="10"
                              x1="32.9"
                              y1="88.6"
                              x2="34"
                              y2="91.4"
                            />
                          </g>
                        </g>
                      </g>
                      <g id="wheel2" class="wheel2">
                        <path
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          d="M49.7,93.7c-1.8,4.7,0.4,9.8,5.1,11.7
                                                                                         c4.7,1.8,9.8-0.4,11.7-5.1c1.8-4.7-0.4-9.8-5.1-11.7C56.7,86.8,51.5,89.1,49.7,93.7z"
                        />
                        <circle
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          cx="58"
                          cy="97"
                          r="3"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="60.6"
                          y1="90.5"
                          x2="61.3"
                          y2="88.6"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="64.6"
                          y1="99.6"
                          x2="66.4"
                          y2="100.3"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="55.5"
                          y1="103.5"
                          x2="54.7"
                          y2="105.4"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="51.5"
                          y1="94.5"
                          x2="49.7"
                          y2="93.7"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="49.8"
                          y1="100.6"
                          x2="52.5"
                          y2="99.4"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="61.6"
                          y1="105.3"
                          x2="60.4"
                          y2="102.5"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="66.3"
                          y1="93.4"
                          x2="63.5"
                          y2="94.6"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="54.5"
                          y1="88.8"
                          x2="55.6"
                          y2="91.5"
                        />
                      </g>
                      <g id="wheel1" class="wheel1">
                        <path
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          d="M110.8,93.4c-2,4.6,0,9.8,4.6,11.9
                                                                                         c4.6,2,9.8,0,11.9-4.6c2-4.6,0-9.8-4.6-11.9C118.1,86.8,112.8,88.8,110.8,93.4z"
                        />
                        <circle
                          fill="#FFFFFF"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          cx="119"
                          cy="97"
                          r="3"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="121.9"
                          y1="90.6"
                          x2="122.7"
                          y2="88.8"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="125.4"
                          y1="99.9"
                          x2="127.2"
                          y2="100.7"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="116.2"
                          y1="103.4"
                          x2="115.4"
                          y2="105.2"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="112.6"
                          y1="94.2"
                          x2="110.8"
                          y2="93.4"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="110.6"
                          y1="100.2"
                          x2="113.4"
                          y2="99.2"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="122.2"
                          y1="105.4"
                          x2="121.2"
                          y2="102.6"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="127.4"
                          y1="93.8"
                          x2="124.6"
                          y2="94.9"
                        />
                        <line
                          fill="#F2F2F2"
                          stroke="#CCCCCC"
                          stroke-width="2"
                          stroke-miterlimit="10"
                          x1="115.8"
                          y1="88.6"
                          x2="116.9"
                          y2="91.4"
                        />
                      </g>
                      <line
                        id="floor"
                        class="floor"
                        fill="none"
                        stroke="#E8E8E8"
                        stroke-width="2"
                        stroke-miterlimit="10"
                        x1="12"
                        y1="108"
                        x2="140"
                        y2="108"
                      />
                    </svg>
                  </div>
                </div>
              </Col>
              <Col xs={12} md={6} className="right">
                <h3>
                  Our car hauling service delivers your <br></br>
                  <span>vehicle to its destination.</span>
                </h3>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                  Ut enim ad minim veniam, quis nostrud exercitation ullamco
                  laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                  irure dolor in reprehenderit in voluptate velit esse cillum
                  dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                  cupidatat non proident, sunt in culpa qui officia deserunt
                  mollit anim id est laborum.
                </p>
              </Col>
            </Row>
          </Carousel>
        </Container>
      </section>
    );
  }
}
